# 配置端口
server:
  port: 9999
spring:
  profiles:
    active: pro
  datasource:
    # 基础属性
    # 腾讯云 mysql 数据库连接
    url: jdbc:mysql://cdb-csnz8qhs.cd.tencentcdb.com:10087/model-code-fusheng?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: code-fusheng
    # 可以不配置，根据url自动识别，建议配置
    driver-class-name: com.mysql.cj.jdbc.Driver


